### PR TITLE
New design

### LINKED ISSUE #18: Use a new email template
https://github.com/leemunroe/responsive-html-email-template

### PR DESCRIPTION
**Pull request by ArsalanSavand**
Fixes #18

### CODE REVIEW

**Review by Alir3z4 — APPROVED** [review]

**Comment by Alir3z4** [comment]
@AmirSavand when is this going to be ready my friend ?

**Comment by AmirSavand** [comment]
@Alir3z4 taking a long time, because we need to decide what to do with the rendering.
For now, same old html style.

**Comment by Alir3z4** [comment]
Yeah, keep it the same things as it is.
Once the templates have been done, we can change the rendering easily.

What do you need on the backend for this, that inline css thingy ?
Please make a report on the backend so I can work on it, include the library as well.

**Comment by AmirSavand** [comment]
Ok

**Comment by Alir3z4** [comment]
Let's have this merged into master and get it all done

**Pull request merged**
